{"name": "\n    тест: появление ошибки при попытке входа в систему с несуществующем логоном\n    ", "status": "passed", "description": "\n        тест: появление ошибки при попытке входа в систему\n        с несуществующем логином.\n        ", "steps": [{"name": "Авторизиция курьера", "status": "passed", "steps": [{"name": "Отправка post запроса", "status": "passed", "parameters": [{"name": "url", "value": "'https://qa-scooter.praktikum-services.ru/api/v1/courier/login'"}, {"name": "data", "value": "{'login': 'arfblcmkdy', 'password': 'fgckxheddh'}"}], "start": 1749200578241, "stop": 1749200578356}, {"name": "Получение статуса ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [404]>"}], "start": 1749200578357, "stop": 1749200578357}, {"name": "Получение json текста ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [404]>"}], "start": 1749200578357, "stop": 1749200578357}], "parameters": [{"name": "login", "value": "'arfblcmkdy'"}, {"name": "password", "value": "'fgckxheddh'"}], "start": 1749200578240, "stop": 1749200578357}], "start": 1749200578240, "stop": 1749200578358, "uuid": "018b83a9-e55a-4859-80c8-356c1b7a3a30", "historyId": "fb6cde0c8e178588b6fdf4a9aa5c3698", "testCaseId": "fb6cde0c8e178588b6fdf4a9aa5c3698", "fullName": "tests.test_courier.TestCaseCourier#test_an_error_occurs_with_a_non_existent_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('create_or_update_bd')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCaseCourier"}, {"name": "host", "value": "dynamic-005-005-005-243.5.5.pool.telefonica.de"}, {"name": "thread", "value": "2119-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}